//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circuit_Layout.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Circuit_Layout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Anufriev Yurii Andreevich.
        /// </summary>
        public static string aw_anufriev {
            get {
                return ResourceManager.GetString("aw_anufriev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Danilov Maxim Alekseevich.
        /// </summary>
        public static string aw_danilov {
            get {
                return ResourceManager.GetString("aw_danilov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Development (Dream)Team:.
        /// </summary>
        public static string aw_dev {
            get {
                return ResourceManager.GetString("aw_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Nazarova Anna Vasilievna.
        /// </summary>
        public static string aw_nazarova {
            get {
                return ResourceManager.GetString("aw_nazarova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Sorvanova Anna Konstantinovna.
        /// </summary>
        public static string aw_sorvanova {
            get {
                return ResourceManager.GetString("aw_sorvanova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Circuit Layout.
        /// </summary>
        public static string aw_title {
            get {
                return ResourceManager.GetString("aw_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        public static string cc_cb_run {
            get {
                return ResourceManager.GetString("cc_cb_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop simulation.
        /// </summary>
        public static string cc_cb_stop {
            get {
                return ResourceManager.GetString("cc_cb_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CHAINS:.
        /// </summary>
        public static string cc_cd_chains {
            get {
                return ResourceManager.GetString("cc_cd_chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CONTOURS:.
        /// </summary>
        public static string cc_cd_contours {
            get {
                return ResourceManager.GetString("cc_cd_contours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EQUATIONS:.
        /// </summary>
        public static string cc_cd_equations {
            get {
                return ResourceManager.GetString("cc_cd_equations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equations by Kirchhoff rule №1:.
        /// </summary>
        public static string cc_cd_rule1count {
            get {
                return ResourceManager.GetString("cc_cd_rule1count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equations by Kirchhoff rule №2:.
        /// </summary>
        public static string cc_cd_rule2count {
            get {
                return ResourceManager.GetString("cc_cd_rule2count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string cc_cm_edit {
            get {
                return ResourceManager.GetString("cc_cm_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string cc_cm_remove {
            get {
                return ResourceManager.GetString("cc_cm_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove connector.
        /// </summary>
        public static string cc_connector_cm_remove {
            get {
                return ResourceManager.GetString("cc_connector_cm_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cant calculate eqations values.
        /// </summary>
        public static string cc_ex_kramercounterexception {
            get {
                return ResourceManager.GetString("cc_ex_kramercounterexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layout simulation exception.
        /// </summary>
        public static string cc_ex_layoutsimexception {
            get {
                return ResourceManager.GetString("cc_ex_layoutsimexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resistor Rx is already placed.
        /// </summary>
        public static string cc_ex_xresistorisplaced {
            get {
                return ResourceManager.GetString("cc_ex_xresistorisplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ew_bt_cancel {
            get {
                return ResourceManager.GetString("ew_bt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string ew_bt_ok {
            get {
                return ResourceManager.GetString("ew_bt_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display Voltage:.
        /// </summary>
        public static string ew_displatvoltage {
            get {
                return ResourceManager.GetString("ew_displatvoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display mode:.
        /// </summary>
        public static string ew_displaymode {
            get {
                return ResourceManager.GetString("ew_displaymode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length.
        /// </summary>
        public static string ew_displaymode_length {
            get {
                return ResourceManager.GetString("ew_displaymode_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resistance.
        /// </summary>
        public static string ew_displaymode_resistance {
            get {
                return ResourceManager.GetString("ew_displaymode_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Division:.
        /// </summary>
        public static string ew_division {
            get {
                return ResourceManager.GetString("ew_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Ampermeter.
        /// </summary>
        public static string ew_edit_ampermeter {
            get {
                return ResourceManager.GetString("ew_edit_ampermeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Battery.
        /// </summary>
        public static string ew_edit_battery {
            get {
                return ResourceManager.GetString("ew_edit_battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Potentiometer.
        /// </summary>
        public static string ew_edit_potentiometer {
            get {
                return ResourceManager.GetString("ew_edit_potentiometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Reohord.
        /// </summary>
        public static string ew_edit_reohord {
            get {
                return ResourceManager.GetString("ew_edit_reohord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Resistor.
        /// </summary>
        public static string ew_edit_resistor {
            get {
                return ResourceManager.GetString("ew_edit_resistor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Resistor X.
        /// </summary>
        public static string ew_edit_resistorx {
            get {
                return ResourceManager.GetString("ew_edit_resistorx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editable:.
        /// </summary>
        public static string ew_editable {
            get {
                return ResourceManager.GetString("ew_editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EMF:.
        /// </summary>
        public static string ew_emf {
            get {
                return ResourceManager.GetString("ew_emf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max Resistance:.
        /// </summary>
        public static string ew_maxresistance {
            get {
                return ResourceManager.GetString("ew_maxresistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string ew_name {
            get {
                return ResourceManager.GetString("ew_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resistance:.
        /// </summary>
        public static string ew_resistance {
            get {
                return ResourceManager.GetString("ew_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ex_error {
            get {
                return ResourceManager.GetString("ex_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Circuit Layout save files.
        /// </summary>
        public static string mw_c_savefiles {
            get {
                return ResourceManager.GetString("mw_c_savefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error loading file.
        /// </summary>
        public static string mw_ex_errorloadingfile {
            get {
                return ResourceManager.GetString("mw_ex_errorloadingfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No task selected.
        /// </summary>
        public static string mw_ex_notaskselected {
            get {
                return ResourceManager.GetString("mw_ex_notaskselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected task number does not match.
        /// </summary>
        public static string mw_ex_tasknumberdoesntmatch {
            get {
                return ResourceManager.GetString("mw_ex_tasknumberdoesntmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong input file.
        /// </summary>
        public static string mw_ex_wronginputfile {
            get {
                return ResourceManager.GetString("mw_ex_wronginputfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exercises.
        /// </summary>
        public static string mw_mm_exercises {
            get {
                return ResourceManager.GetString("mw_mm_exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string mw_mm_file {
            get {
                return ResourceManager.GetString("mw_mm_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        public static string mw_mm_file_load {
            get {
                return ResourceManager.GetString("mw_mm_file_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string mw_mm_file_print {
            get {
                return ResourceManager.GetString("mw_mm_file_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string mw_mm_file_save {
            get {
                return ResourceManager.GetString("mw_mm_file_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        public static string mw_mm_file_saveas {
            get {
                return ResourceManager.GetString("mw_mm_file_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string mw_mm_help {
            get {
                return ResourceManager.GetString("mw_mm_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About....
        /// </summary>
        public static string mw_mm_help_about {
            get {
                return ResourceManager.GetString("mw_mm_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show help.
        /// </summary>
        public static string mw_mm_help_showhelp {
            get {
                return ResourceManager.GetString("mw_mm_help_showhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layout.
        /// </summary>
        public static string mw_mm_layout {
            get {
                return ResourceManager.GetString("mw_mm_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear Layout.
        /// </summary>
        public static string mw_mm_layout_clearlayout {
            get {
                return ResourceManager.GetString("mw_mm_layout_clearlayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rx Resistance.
        /// </summary>
        public static string mw_mm_layout_rxresistance {
            get {
                return ResourceManager.GetString("mw_mm_layout_rxresistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formalization.
        /// </summary>
        public static string mw_tc_formalization {
            get {
                return ResourceManager.GetString("mw_tc_formalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layout.
        /// </summary>
        public static string mw_tc_layout {
            get {
                return ResourceManager.GetString("mw_tc_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check answer.
        /// </summary>
        public static string tc_bt_checkanswer {
            get {
                return ResourceManager.GetString("tc_bt_checkanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update diagrams.
        /// </summary>
        public static string tc_bt_updatediagrams {
            get {
                return ResourceManager.GetString("tc_bt_updatediagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formalization print.
        /// </summary>
        public static string tc_c_formalization_print {
            get {
                return ResourceManager.GetString("tc_c_formalization_print", resourceCulture);
            }
        }
    }
}
